### ISSUE TITLE
triple pattern queries

### ISSUE THREAD

**Issue by KonradHoeffner** [KonradHoeffner/hdt#3]
Right now there is only an option to iterate over *all* triples, which is inefficient for large graphs.
Implement triple pattern queries and add tests.

- [x] triples_with_s
- [x] triples_with_o
- [x] triples_with_p

**Comment by chrysn** [comment]
Once these are in, this might make a good backend for SPARQL engines as well, especially for data sets exceeding RAM, which might then be efficiently usable without the further need to create a dedicated SPARQL-engine-specific index on.

**Comment by KonradHoeffner** [comment]
Good point! This is even mentioned in the [RDF HDT file format internals documentation](https://www.rdfhdt.org/hdt-internals/). Quote:

> Nevertheless, it does not support all kind of triple patterns directly on that structure, it is restricted to SPO, SP?, S?? and ??? queries. Thus, once the HDT-encoded dataset is loaded into the memory hierarchy, we slightly enrich the representation with additional succinct data structures to support the remaining triple patterns to be solved efficiently. The final fully queryable representation is called HDT-FoQ: HDT Focused on Querying. In the following we briefly present the main extensions. The technical specification of the structures can be found in our publication [(Martínez-Prieto, Arias, and Fernández 2012)](https://www.rdfhdt.org/hdt-internals/#maf).

However I think this specific use case of a backend for a SPARQL engine with data exceeding RAM seems to be a already covered by the triple store library [terminus-store](https://crates.io/crates/terminus-store), whose format is based on HDT. I have not used terminusdb-store but it seems to have functions for persisting data on disk, while when using this library you would have to implement all that.
