### ISSUE TITLE
Editorial comments on JOSS paper

### ISSUE THREAD

**Issue by osorensen** [KonradHoeffner/hdt#31]
I'm reading through the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5114) now, and will post comments here.

On line 40, I cannot see that HDT-FoQ has been defined yet, so please introduce it here. I notice that it's introduced in the caption to Figure 2, but please do it in the main text also.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/21175639/234376168-4789a32b-ffb0-4641-8a7e-b4762b6b8e4e.png">

**Comment by KonradHoeffner** [comment]
Defined HDT-FoQ in the main text in https://github.com/KonradHoeffner/hdt/commit/ad4a388322955378f9bde6cdc95b272ca56d3262.
